[package]
name = "r2deob"
version = "0.1.0"
authors = ["0xrmc <me@09f9.org>"]
edition = "2018"

[dependencies]
r2pipe = "0.4.0"
serde_json = "1.0.27"
rand = "0.5.5"
rsmt2 = "0.9.11"
#programinduction = "0.7.4"
calculate = "0.5.1"
